spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/recipenote/testDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always
server:
  servlet:
    multipart:
      location: C:\Users\ywl08\upload
      max-file-size: 10MB
      max-request-size: 50MB
image:
  local: true