spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/recipenote/testDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      mode: never

server:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
image:
  local: true

resource:
  path: file:///C:/Users/ywl08/resource/
upload:
  path: /upload/**