spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/recipenote
    driver-class-name: org.postgresql.Driver
    username: recipenote
    password: password
  sql:
    init:
      mode: never

server:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
image:
  local: false

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1