drop table if exists affiliate CASCADE;
drop table if exists amount_of_ingredient CASCADE;
drop table if exists comment CASCADE;
drop table if exists ingredient CASCADE;
drop table if exists recipe CASCADE;
drop table if exists role CASCADE;
drop table if exists store CASCADE;
drop table if exists usr CASCADE;
drop table if exists user_role CASCADE;



create table affiliate
(
    id          int8 generated by default as identity,
    created_at  timestamp,
    updated_at  timestamp,
    description varchar(255) not null,
    name        varchar(255) not null,
    primary key (id)
);


create table amount_of_ingredient
(
    id            int8 generated by default as identity,
    amount        float8,
    ingredient_id int8,
    recipe_id     int8,
    primary key (id)
);


create table comment
(
    id          int8 generated by default as identity,
    created_at  timestamp,
    updated_at  timestamp,
    description varchar(255) not null,
    recipe_id   int8         not null,
    user_id     int8         not null,
    primary key (id)
);


create table ingredient
(
    id         int8 generated by default as identity,
    created_at timestamp,
    updated_at timestamp,
    name       varchar(255) not null,
    price      float8,
    primary key (id)
);


create table recipe
(
    id             int8 generated by default as identity,
    created_at     timestamp,
    updated_at     timestamp,
    affiliate_id   int8,
    content        varchar(1000) not null,
    is_public      boolean       not null,
    name           varchar(255)  not null,
    store_id       int8,
    thumbnail_path varchar(255),
    user_id        int8          not null,
    primary key (id)
);


create table role
(
    id   int8 generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);


create table store
(
    id           int8 generated by default as identity,
    created_at   timestamp,
    updated_at   timestamp,
    affiliate_id int8         not null,
    description  varchar(255),
    latitude     float8,
    longitude    float8,
    place_id     varchar(255),
    logo_url     varchar(255),
    name         varchar(255) not null,
    primary key (id)
);


create table user_role
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);


create table usr
(
    user_id      int8 generated by default as identity,
    created_at   timestamp,
    updated_at   timestamp,
    affiliate_id int8,
    avatar_url   varchar(255),
    enabled      boolean      not null,
    name         varchar(255) not null,
    password     varchar(255) not null,
    username     varchar(255) not null,
    primary key (user_id)
);


alter table if exists affiliate
    add constraint UK_k303s6m10cc5ybjcy470pkax8 unique (name);


alter table if exists store
    add constraint UK_d0p5ly1cv6guij7sq1mbnr8ec unique (name);


alter table if exists usr
    add constraint UK_dfui7gxngrgwn9ewee3ogtgym unique (username);


alter table if exists amount_of_ingredient
    add constraint FKeoy685ej8s4cbwv84p8vp8xmp
        foreign key (ingredient_id)
            references ingredient;


alter table if exists amount_of_ingredient
    add constraint FK26fwlyr70x0neu9besaf68lx1
        foreign key (recipe_id)
            references recipe;


alter table if exists comment
    add constraint FKe5i1rxybcm40jcn98fj1jmvit
        foreign key (recipe_id)
            references recipe;


alter table if exists comment
    add constraint FKgcgdcgly6u49hf4g8y2di3g4p
        foreign key (user_id)
            references usr;


alter table if exists recipe
    add constraint FKf6vfkhk3a391o4sdsk0w717wn
        foreign key (affiliate_id)
            references affiliate;


alter table if exists recipe
    add constraint FK2fhnivbwc4v39wdq9lp3ryoam
        foreign key (store_id)
            references store;


alter table if exists recipe
    add constraint FK41os70oqbxog987fsbn6sus5i
        foreign key (user_id)
            references usr;


alter table if exists store
    add constraint FKokmptx2g80t56urw269wcllvo
        foreign key (affiliate_id)
            references affiliate;


alter table if exists user_role
    add constraint FKa68196081fvovjhkek5m97n3y
        foreign key (role_id)
            references role;


alter table if exists user_role
    add constraint FKfpm8swft53ulq2hl11yplpr5
        foreign key (user_id)
            references usr;


alter table if exists usr
    add constraint FKbdjgo9yx21ld4dud9yfaum55a
        foreign key (affiliate_id)
            references affiliate;